# Site settings

title: nodexploit
description: > # this means to ignore newlines until "baseurl:"
  Programming, exploits and hacks. Two computer scientists making projects,
  writting stuffs and playing with technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nodexploit.com" # the base hostname & protocol for your site
icon:
    base_url: "/assets/img/header.jpg"
    width: 159
    height: 136

# Authors
authors:
    soasada:
        name: Nicolás Vargas Ortega
        display_name: soasada
        email: nvortega92@gmail.com
        github: soasada
    soutoner:
        name: Adrián González Leiva
        display_name: soutoner
        github: soutoner

# Build settings
markdown: kramdown
