# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nodeXploit
email: z0rtecx@eml.cc
description: > # this means to ignore newlines until "baseurl:"
  Programming, exploits and hacks. Two computer scientists making projects,
  writting stuffs and playing with technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nodexploit.com" # the base hostname & protocol for your site
twitter_username: #
github_username:  soasada

# Build settings
markdown: kramdown
