# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nodexploit.com" # the base hostname & protocol for your site

authors:
  soasada:
      display_name: Nicolas Vargas
      gravatar: 82aecf33c6b2fb5b6fae0db3a476361e
      email: soasada@nodexploit.com
      about_me:
      about:
      github: soasada
  soutoner:
    display_name: Adrian Gonzalez
    gravatar: f772263b9b40093644f33332b1f2bed1
    email: soutoner@nodexploit.com
    about_me:
    about:
    github: soutoner

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: nodexploit
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Programming, exploits, tricks and more" # used by search engines

  # Header and footer text
  # header_text: >
  # header_text_feature_image:
  footer_text: >
   nodexploit | Copyright All Rights Reserved © 2016
  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: soasada/soasada.github.io
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  # twitter: "twitter"
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-61823229-1 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: nodexploit
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
